version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/src/main/resources/prometheus.yml

#  bitcoin:
#    image: bitcoin/bitcoin:26.0
#    container_name: bitcoin
#    ports:
#      - "8333:8333"
#    volumes:
#      - bitcoin_data:/root/.bitcoin

#volumes:
#  postgres_data: