spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_qr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      #        - org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    #        - org.apache.kafka.common.serialization.StringSerializer
#    #    batch-size: 16384
#
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: myGroup
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      #        - org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      #        - org.apache.kafka.common.serialization.StringSerializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: postgres
#    password: postgres
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            required: true
#            enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: pojk2499W4GNOUwgnNUIjytwRNmiraegoanepMGigiwendwanmGNM0min4G9UNwg4OGI4N0
  lifetime: 50m

